require 'rails_helper'

describe GithubWebhooksController do
  describe "#github_pull_request" do
    it "returns the file contents given a repo, filename, and commit sha" do
      body = {
        "action": "opened",
        "number": 15,
        "pull_request": {
          "url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/15",
          "id": 93852699,
          "html_url": "https://github.com/gemfarmer/github_webhook/pull/15",
          "diff_url": "https://github.com/gemfarmer/github_webhook/pull/15.diff",
          "patch_url": "https://github.com/gemfarmer/github_webhook/pull/15.patch",
          "issue_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/15",
          "number": 15,
          "state": "open",
          "locked": false,
          "title": "New pr",
          "user": {
            "login": "gemfarmer",
            "id": 4803473,
            "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/gemfarmer",
            "html_url": "https://github.com/gemfarmer",
            "followers_url": "https://api.github.com/users/gemfarmer/followers",
            "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
            "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
            "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
            "repos_url": "https://api.github.com/users/gemfarmer/repos",
            "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
            "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
            "type": "User",
            "site_admin": false
          },
          "body": "look at this PR! ",
          "created_at": "2016-11-15T21:34:14Z",
          "updated_at": "2016-11-15T21:34:14Z",
          "closed_at": nil,
          "merged_at": nil,
          "merge_commit_sha": "a63fd9d8bdb027416e83aadd4c175760e0545310",
          "assignee": nil,
          "assignees": [

          ],
          "milestone": nil,
          "commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/15/commits",
          "review_comments_url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/15/comments",
          "review_comment_url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/comments{/number}",
          "comments_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/15/comments",
          "statuses_url": "https://api.github.com/repos/gemfarmer/github_webhook/statuses/e76eb9f5cd114c511a569b14a9bb9a7b475141a2",
          "head": {
            "label": "gemfarmer:new-pr",
            "ref": "new-pr",
            "sha": "e76eb9f5cd114c511a569b14a9bb9a7b475141a2",
            "user": {
              "login": "gemfarmer",
              "id": 4803473,
              "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
              "gravatar_id": "",
              "url": "https://api.github.com/users/gemfarmer",
              "html_url": "https://github.com/gemfarmer",
              "followers_url": "https://api.github.com/users/gemfarmer/followers",
              "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
              "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
              "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
              "repos_url": "https://api.github.com/users/gemfarmer/repos",
              "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
              "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
              "type": "User",
              "site_admin": false
            },
            "repo": {
              "id": 71174655,
              "name": "github_webhook",
              "full_name": "gemfarmer/github_webhook",
              "owner": {
                "login": "gemfarmer",
                "id": 4803473,
                "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/gemfarmer",
                "html_url": "https://github.com/gemfarmer",
                "followers_url": "https://api.github.com/users/gemfarmer/followers",
                "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
                "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
                "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
                "repos_url": "https://api.github.com/users/gemfarmer/repos",
                "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
                "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
                "type": "User",
                "site_admin": false
              },
              "private": false,
              "html_url": "https://github.com/gemfarmer/github_webhook",
              "description": nil,
              "fork": false,
              "url": "https://api.github.com/repos/gemfarmer/github_webhook",
              "forks_url": "https://api.github.com/repos/gemfarmer/github_webhook/forks",
              "keys_url": "https://api.github.com/repos/gemfarmer/github_webhook/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/gemfarmer/github_webhook/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/gemfarmer/github_webhook/teams",
              "hooks_url": "https://api.github.com/repos/gemfarmer/github_webhook/hooks",
              "issue_events_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/events{/number}",
              "events_url": "https://api.github.com/repos/gemfarmer/github_webhook/events",
              "assignees_url": "https://api.github.com/repos/gemfarmer/github_webhook/assignees{/user}",
              "branches_url": "https://api.github.com/repos/gemfarmer/github_webhook/branches{/branch}",
              "tags_url": "https://api.github.com/repos/gemfarmer/github_webhook/tags",
              "blobs_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/gemfarmer/github_webhook/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/gemfarmer/github_webhook/languages",
              "stargazers_url": "https://api.github.com/repos/gemfarmer/github_webhook/stargazers",
              "contributors_url": "https://api.github.com/repos/gemfarmer/github_webhook/contributors",
              "subscribers_url": "https://api.github.com/repos/gemfarmer/github_webhook/subscribers",
              "subscription_url": "https://api.github.com/repos/gemfarmer/github_webhook/subscription",
              "commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/gemfarmer/github_webhook/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/gemfarmer/github_webhook/contents/{+path}",
              "compare_url": "https://api.github.com/repos/gemfarmer/github_webhook/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/gemfarmer/github_webhook/merges",
              "archive_url": "https://api.github.com/repos/gemfarmer/github_webhook/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/gemfarmer/github_webhook/downloads",
              "issues_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues{/number}",
              "pulls_url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/gemfarmer/github_webhook/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/gemfarmer/github_webhook/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/gemfarmer/github_webhook/labels{/name}",
              "releases_url": "https://api.github.com/repos/gemfarmer/github_webhook/releases{/id}",
              "deployments_url": "https://api.github.com/repos/gemfarmer/github_webhook/deployments",
              "created_at": "2016-10-17T19:41:56Z",
              "updated_at": "2016-10-17T19:41:56Z",
              "pushed_at": "2016-11-15T21:34:14Z",
              "git_url": "git://github.com/gemfarmer/github_webhook.git",
              "ssh_url": "git@github.com:gemfarmer/github_webhook.git",
              "clone_url": "https://github.com/gemfarmer/github_webhook.git",
              "svn_url": "https://github.com/gemfarmer/github_webhook",
              "homepage": nil,
              "size": 39,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": nil,
              "has_issues": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "open_issues_count": 15,
              "forks": 0,
              "open_issues": 15,
              "watchers": 0,
              "default_branch": "master"
            }
          },
          "base": {
            "label": "gemfarmer:master",
            "ref": "master",
            "sha": "b0b50800ee737d086e0411a21cd0432832c7756b",
            "user": {
              "login": "gemfarmer",
              "id": 4803473,
              "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
              "gravatar_id": "",
              "url": "https://api.github.com/users/gemfarmer",
              "html_url": "https://github.com/gemfarmer",
              "followers_url": "https://api.github.com/users/gemfarmer/followers",
              "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
              "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
              "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
              "repos_url": "https://api.github.com/users/gemfarmer/repos",
              "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
              "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
              "type": "User",
              "site_admin": false
            },
            "repo": {
              "id": 71174655,
              "name": "github_webhook",
              "full_name": "gemfarmer/github_webhook",
              "owner": {
                "login": "gemfarmer",
                "id": 4803473,
                "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/gemfarmer",
                "html_url": "https://github.com/gemfarmer",
                "followers_url": "https://api.github.com/users/gemfarmer/followers",
                "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
                "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
                "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
                "repos_url": "https://api.github.com/users/gemfarmer/repos",
                "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
                "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
                "type": "User",
                "site_admin": false
              },
              "private": false,
              "html_url": "https://github.com/gemfarmer/github_webhook",
              "description": nil,
              "fork": false,
              "url": "https://api.github.com/repos/gemfarmer/github_webhook",
              "forks_url": "https://api.github.com/repos/gemfarmer/github_webhook/forks",
              "keys_url": "https://api.github.com/repos/gemfarmer/github_webhook/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/gemfarmer/github_webhook/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/gemfarmer/github_webhook/teams",
              "hooks_url": "https://api.github.com/repos/gemfarmer/github_webhook/hooks",
              "issue_events_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/events{/number}",
              "events_url": "https://api.github.com/repos/gemfarmer/github_webhook/events",
              "assignees_url": "https://api.github.com/repos/gemfarmer/github_webhook/assignees{/user}",
              "branches_url": "https://api.github.com/repos/gemfarmer/github_webhook/branches{/branch}",
              "tags_url": "https://api.github.com/repos/gemfarmer/github_webhook/tags",
              "blobs_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/gemfarmer/github_webhook/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/gemfarmer/github_webhook/languages",
              "stargazers_url": "https://api.github.com/repos/gemfarmer/github_webhook/stargazers",
              "contributors_url": "https://api.github.com/repos/gemfarmer/github_webhook/contributors",
              "subscribers_url": "https://api.github.com/repos/gemfarmer/github_webhook/subscribers",
              "subscription_url": "https://api.github.com/repos/gemfarmer/github_webhook/subscription",
              "commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/gemfarmer/github_webhook/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/gemfarmer/github_webhook/contents/{+path}",
              "compare_url": "https://api.github.com/repos/gemfarmer/github_webhook/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/gemfarmer/github_webhook/merges",
              "archive_url": "https://api.github.com/repos/gemfarmer/github_webhook/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/gemfarmer/github_webhook/downloads",
              "issues_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues{/number}",
              "pulls_url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/gemfarmer/github_webhook/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/gemfarmer/github_webhook/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/gemfarmer/github_webhook/labels{/name}",
              "releases_url": "https://api.github.com/repos/gemfarmer/github_webhook/releases{/id}",
              "deployments_url": "https://api.github.com/repos/gemfarmer/github_webhook/deployments",
              "created_at": "2016-10-17T19:41:56Z",
              "updated_at": "2016-10-17T19:41:56Z",
              "pushed_at": "2016-11-15T21:34:14Z",
              "git_url": "git://github.com/gemfarmer/github_webhook.git",
              "ssh_url": "git@github.com:gemfarmer/github_webhook.git",
              "clone_url": "https://github.com/gemfarmer/github_webhook.git",
              "svn_url": "https://github.com/gemfarmer/github_webhook",
              "homepage": nil,
              "size": 39,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": nil,
              "has_issues": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "open_issues_count": 15,
              "forks": 0,
              "open_issues": 15,
              "watchers": 0,
              "default_branch": "master"
            }
          },
          "_links": {
            "self": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/15"
            },
            "html": {
              "href": "https://github.com/gemfarmer/github_webhook/pull/15"
            },
            "issue": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/issues/15"
            },
            "comments": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/issues/15/comments"
            },
            "review_comments": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/15/comments"
            },
            "review_comment": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/comments{/number}"
            },
            "commits": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/pulls/15/commits"
            },
            "statuses": {
              "href": "https://api.github.com/repos/gemfarmer/github_webhook/statuses/e76eb9f5cd114c511a569b14a9bb9a7b475141a2"
            }
          },
          "merged": false,
          "mergeable": true,
          "mergeable_state": "clean",
          "merged_by": nil,
          "comments": 0,
          "review_comments": 0,
          "commits": 63,
          "additions": 38,
          "deletions": 0,
          "changed_files": 5
        },
        "repository": {
          "id": 71174655,
          "name": "github_webhook",
          "full_name": "gemfarmer/github_webhook",
          "owner": {
            "login": "gemfarmer",
            "id": 4803473,
            "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/gemfarmer",
            "html_url": "https://github.com/gemfarmer",
            "followers_url": "https://api.github.com/users/gemfarmer/followers",
            "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
            "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
            "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
            "repos_url": "https://api.github.com/users/gemfarmer/repos",
            "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
            "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
            "type": "User",
            "site_admin": false
          },
          "private": false,
          "html_url": "https://github.com/gemfarmer/github_webhook",
          "description": nil,
          "fork": false,
          "url": "https://api.github.com/repos/gemfarmer/github_webhook",
          "forks_url": "https://api.github.com/repos/gemfarmer/github_webhook/forks",
          "keys_url": "https://api.github.com/repos/gemfarmer/github_webhook/keys{/key_id}",
          "collaborators_url": "https://api.github.com/repos/gemfarmer/github_webhook/collaborators{/collaborator}",
          "teams_url": "https://api.github.com/repos/gemfarmer/github_webhook/teams",
          "hooks_url": "https://api.github.com/repos/gemfarmer/github_webhook/hooks",
          "issue_events_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/events{/number}",
          "events_url": "https://api.github.com/repos/gemfarmer/github_webhook/events",
          "assignees_url": "https://api.github.com/repos/gemfarmer/github_webhook/assignees{/user}",
          "branches_url": "https://api.github.com/repos/gemfarmer/github_webhook/branches{/branch}",
          "tags_url": "https://api.github.com/repos/gemfarmer/github_webhook/tags",
          "blobs_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/blobs{/sha}",
          "git_tags_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/tags{/sha}",
          "git_refs_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/refs{/sha}",
          "trees_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/trees{/sha}",
          "statuses_url": "https://api.github.com/repos/gemfarmer/github_webhook/statuses/{sha}",
          "languages_url": "https://api.github.com/repos/gemfarmer/github_webhook/languages",
          "stargazers_url": "https://api.github.com/repos/gemfarmer/github_webhook/stargazers",
          "contributors_url": "https://api.github.com/repos/gemfarmer/github_webhook/contributors",
          "subscribers_url": "https://api.github.com/repos/gemfarmer/github_webhook/subscribers",
          "subscription_url": "https://api.github.com/repos/gemfarmer/github_webhook/subscription",
          "commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/commits{/sha}",
          "git_commits_url": "https://api.github.com/repos/gemfarmer/github_webhook/git/commits{/sha}",
          "comments_url": "https://api.github.com/repos/gemfarmer/github_webhook/comments{/number}",
          "issue_comment_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues/comments{/number}",
          "contents_url": "https://api.github.com/repos/gemfarmer/github_webhook/contents/{+path}",
          "compare_url": "https://api.github.com/repos/gemfarmer/github_webhook/compare/{base}...{head}",
          "merges_url": "https://api.github.com/repos/gemfarmer/github_webhook/merges",
          "archive_url": "https://api.github.com/repos/gemfarmer/github_webhook/{archive_format}{/ref}",
          "downloads_url": "https://api.github.com/repos/gemfarmer/github_webhook/downloads",
          "issues_url": "https://api.github.com/repos/gemfarmer/github_webhook/issues{/number}",
          "pulls_url": "https://api.github.com/repos/gemfarmer/github_webhook/pulls{/number}",
          "milestones_url": "https://api.github.com/repos/gemfarmer/github_webhook/milestones{/number}",
          "notifications_url": "https://api.github.com/repos/gemfarmer/github_webhook/notifications{?since,all,participating}",
          "labels_url": "https://api.github.com/repos/gemfarmer/github_webhook/labels{/name}",
          "releases_url": "https://api.github.com/repos/gemfarmer/github_webhook/releases{/id}",
          "deployments_url": "https://api.github.com/repos/gemfarmer/github_webhook/deployments",
          "created_at": "2016-10-17T19:41:56Z",
          "updated_at": "2016-10-17T19:41:56Z",
          "pushed_at": "2016-11-15T21:34:14Z",
          "git_url": "git://github.com/gemfarmer/github_webhook.git",
          "ssh_url": "git@github.com:gemfarmer/github_webhook.git",
          "clone_url": "https://github.com/gemfarmer/github_webhook.git",
          "svn_url": "https://github.com/gemfarmer/github_webhook",
          "homepage": nil,
          "size": 39,
          "stargazers_count": 0,
          "watchers_count": 0,
          "language": nil,
          "has_issues": true,
          "has_downloads": true,
          "has_wiki": true,
          "has_pages": false,
          "forks_count": 0,
          "mirror_url": nil,
          "open_issues_count": 15,
          "forks": 0,
          "open_issues": 15,
          "watchers": 0,
          "default_branch": "master"
        },
        "sender": {
          "login": "gemfarmer",
          "id": 4803473,
          "avatar_url": "https://avatars.githubusercontent.com/u/4803473?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/gemfarmer",
          "html_url": "https://github.com/gemfarmer",
          "followers_url": "https://api.github.com/users/gemfarmer/followers",
          "following_url": "https://api.github.com/users/gemfarmer/following{/other_user}",
          "gists_url": "https://api.github.com/users/gemfarmer/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/gemfarmer/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/gemfarmer/subscriptions",
          "organizations_url": "https://api.github.com/users/gemfarmer/orgs",
          "repos_url": "https://api.github.com/users/gemfarmer/repos",
          "events_url": "https://api.github.com/users/gemfarmer/events{/privacy}",
          "received_events_url": "https://api.github.com/users/gemfarmer/received_events",
          "type": "User",
          "site_admin": false
        }
      }

      file_contents = [{:sha=>"ccbf6de4f3a6d4a47705cb4c46eaa9c325fb207c",
       :filename=>"jp.md",
       :status=>"modified",
       :additions=>4,
       :deletions=>0,
       :changes=>4,
       :blob_url=>
        "https://github.com/gemfarmer/github_webhook/blob/e76eb9f5cd114c511a569b14a9bb9a7b475141a2/jp.md",
       :raw_url=>
        "https://github.com/gemfarmer/github_webhook/raw/e76eb9f5cd114c511a569b14a9bb9a7b475141a2/jp.md",
       :contents_url=>
        "https://api.github.com/repos/gemfarmer/github_webhook/contents/jp.md?ref=e76eb9f5cd114c511a569b14a9bb9a7b475141a2",
       :patch=>
        "@@ -1 +1,5 @@\n start new file\n+more text here\n+even more\n+and more\n+..."}
      ]

      subject.request.headers['X-Hub-Signature'] = "sha1=c6bef5cb25f01678b535d87162d6cda6e12c7da0"
      subject.request.headers['Content-Type'] = 'application/json'
      subject.request.headers['X-GitHub-Event'] = 'pull_request'

      pull_request_files = instance_double(PullRequestFiles)
      expect(PullRequestFiles).to receive(:new).
        with('gemfarmer/github_webhook', 'e76eb9f5cd114c511a569b14a9bb9a7b475141a2').
        and_return(pull_request_files)
      expect(pull_request_files).to receive(:changed_files).and_return(file_contents)
      # expect(GithubFileContents).to receive(:new).with('gemfarmer/github_webhook', )

      post :create, body

    end
  end
end
